Repository awslabs/syne-tune, pull requests merged in 2023-06, with the labels that each got.

#689 feat: Add Conformal Quantile Regression method from ICML paper.
  .github/workflows/end-to-end-tests.yml
  examples/launch_cqr_nasbench201.py
  syne_tune/optimizer/baselines.py
  syne_tune/optimizer/schedulers/searchers/conformal/surrogate/conformalized_quantile_regression_model.py
  syne_tune/optimizer/schedulers/searchers/conformal/surrogate/quantile_regression_model.py
  syne_tune/optimizer/schedulers/searchers/conformal/surrogate/quantile_regression_surrogate.py
  syne_tune/optimizer/schedulers/searchers/conformal/surrogate/surrogate_model.py
  syne_tune/optimizer/schedulers/searchers/conformal/surrogate/symmetric_conformalized_quantile_regression_model.py
  syne_tune/optimizer/schedulers/searchers/conformal/surrogate_searcher.py
  syne_tune/optimizer/schedulers/searchers/searcher_factory.py
  syne_tune/optimizer/schedulers/transfer_learning/quantile_based/quantile_based_searcher.py
  tst/schedulers/test_schedulers_api.py
Labels: feature

#702 fix: Command line arguments of benchmarking
  benchmarking/commons/hpo_main_local.py
  benchmarking/commons/hpo_main_sagemaker.py
  benchmarking/commons/launch_remote_local.py
  benchmarking/commons/launch_remote_sagemaker.py
Labels: fix

#701 refactor: Clean up transformer_wikitext2 code
  benchmarking/commons/benchmark_definitions/transformer_wikitext2.py
  benchmarking/training_scripts/transformer_wikitext2/training_script.py
Labels: refactor

#705 docs: Tutorial on experimentation
  benchmarking/nursery/demo_experiment/__init__.py
  benchmarking/nursery/demo_experiment/baselines.py
  benchmarking/nursery/demo_experiment/benchmark_definitions.py
  benchmarking/nursery/demo_experiment/hpo_main.py
  benchmarking/nursery/demo_experiment/launch_remote.py
  benchmarking/nursery/demo_experiment/plot_results.py
  benchmarking/nursery/demo_experiment/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/tutorials/basics/README.rst
  docs/source/tutorials/benchmarking/README.rst
  docs/source/tutorials/experimentation/README.rst
  docs/source/tutorials/experimentation/exp_plotting.rst
  docs/source/tutorials/experimentation/exp_setup.rst
  docs/source/tutorials/experimentation/img/docs-2-fcnet-protein.png
  docs/source/tutorials/multifidelity/README.rst
  docs/source/tutorials/visualization/README.rst
  syne_tune/optimizer/schedulers/hyperband_cost_promotion.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/cost/cost_model.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_predictor.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/sklearn/predictor.py
  syne_tune/optimizer/schedulers/searchers/gp_fifo_searcher.py
Labels: documentation

#706 feat: Plotting for single seed results works as well
  docs/source/tutorials/visualization/comparisons.rst
  syne_tune/experiments/aggregate_results.py
  syne_tune/experiments/plotting.py
Labels: feature

#704 refactor: Simplification in scikit-learn based estimators
  examples/launch_sklearn_surrogate_bo.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_model.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_predictor.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/sklearn/__init__.py
  syne_tune/optimizer/schedulers/searchers/sklearn/sklearn_surrogate_searcher.py
  tst/schedulers/bayesopt/test_sklearn_surrogate.py
Labels: refactor

#696 feat: Allow to transform result dataframe before aggregation in plotting
  docs/source/tutorials/visualization/comparisons.rst
  syne_tune/experiments/experiment_result.py
  syne_tune/experiments/multiobjective.py
  syne_tune/experiments/plotting.py
  syne_tune/optimizer/schedulers/multiobjective/utils.py
  tst/experiments/test_dataframe_transforms.py
  tst/schedulers/multiobjective/test_utils.py
Labels: feature

#711 feat: Multi Surrogate Multi Objective Searcher
  .github/workflows/integ-tests.yml
  README.md
  docs/source/examples.rst
  examples/launch_asha_yahpo.py
  examples/launch_mb_mo_optimization.py
  syne_tune/optimizer/schedulers/multiobjective/multi_surrogate_multi_objective_searcher.py
  syne_tune/optimizer/schedulers/multiobjective/random_scalarization.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/model_transformer.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_model.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/bo_algorithm_components.py
  syne_tune/optimizer/schedulers/searchers/model_based_searcher.py
  tst/schedulers/test_schedulers_api.py
Labels: feature

#717 fix: Fix bug in RemoteLauncher with SageMakerBackend
  .github/workflows/end-to-end-tests.yml
  examples/launch_height_sagemaker_remotely.py
  syne_tune/backend/sagemaker_backend/sagemaker_backend.py
  syne_tune/backend/simulator_backend/simulator_backend.py
  syne_tune/experiments/experiment_result.py
  syne_tune/optimizer/schedulers/median_stopping_rule.py
  syne_tune/optimizer/schedulers/transfer_learning/bounding_box.py
  syne_tune/optimizer/schedulers/transfer_learning/quantile_based/quantile_based_searcher.py
  syne_tune/remote/remote_main.py
Labels: fix

#715 refactor: Remove tuple option for Type[AcquisitionFunction], as this …
  examples/launch_mb_mo_optimization.py
  examples/launch_sklearn_surrogate_bo.py
  syne_tune/optimizer/schedulers/multiobjective/multi_surrogate_multi_objective_searcher.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/base_classes.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/bo_algorithm_components.py
  syne_tune/optimizer/schedulers/searchers/dyhpo/dyhpo_searcher.py
  syne_tune/optimizer/schedulers/searchers/gp_searcher_factory.py
  syne_tune/optimizer/schedulers/searchers/model_based_searcher.py
  syne_tune/optimizer/schedulers/searchers/sklearn/sklearn_surrogate_searcher.py
  tst/schedulers/test_schedulers_api.py
Labels: refactor

#720 fix: Avoid sphinx 7.0.0, since the readthedocs build fails with that
  requirements-dev.txt
Labels: fix

#731 fix: Make sure RemoteLauncher works with requirements.txt which does …
  syne_tune/remote/remote_launcher.py
Labels: fix

#734 fix: Clean up imports so that code runs with core dependencies. Updat…
  .github/workflows/end-to-end-tests.yml
  .github/workflows/integ-tests.yml
  .github/workflows/run-syne-tune.yml
  benchmarking/benchmark_definitions/distilbert_on_imdb.py
  benchmarking/benchmark_definitions/finetune_transformer_glue.py
  benchmarking/benchmark_definitions/finetune_transformer_swag.py
  benchmarking/benchmark_definitions/lstm_wikitext2.py
  benchmarking/benchmark_definitions/mlp_on_fashionmnist.py
  benchmarking/benchmark_definitions/resnet_cifar10.py
  benchmarking/benchmark_definitions/transformer_wikitext2.py
  benchmarking/nursery/odsc_tutorial/transformer_wikitext2/code/transformer_wikitext2_definition.py
  examples/launch_height_config_json.py
  examples/launch_height_sagemaker.py
  examples/launch_height_sagemaker_checkpoints.py
  examples/launch_height_sagemaker_custom_image.py
  examples/launch_height_sagemaker_remotely.py
  examples/launch_height_standalone_scheduler.py
  examples/launch_huggingface_classification.py
  examples/launch_moasha_instance_tuning.py
  examples/launch_tuning_gluonts.py
  requirements-moo.txt
  syne_tune/optimizer/baselines.py
  syne_tune/optimizer/schedulers/multiobjective/__init__.py
  syne_tune/optimizer/schedulers/multiobjective/random_scalarization.py
  syne_tune/optimizer/schedulers/searchers/__init__.py
  syne_tune/optimizer/schedulers/searchers/dyhpo/dyhpo_searcher.py
  syne_tune/optimizer/schedulers/searchers/dyhpo/hyperband_dyhpo.py
  syne_tune/optimizer/schedulers/searchers/utils/hp_ranges_impl.py
  syne_tune/remote/constants.py
  syne_tune/remote/estimators.py
  syne_tune/remote/remote_launcher.py
  tst/trial_backend/checkpoint_sagemaker/test_checkpoint_sagemaker.py
Labels: fix

#709 docs: New tutorial on how to implement Bayesian optimization
  docs/source/index.rst
  docs/source/tutorials/dev_bayesopt/README.rst
  docs/source/tutorials/dev_bayesopt/bo_components.rst
  docs/source/tutorials/dev_bayesopt/gp_model.rst
  docs/source/tutorials/dev_bayesopt/overview_structure.rst
  docs/source/tutorials/dev_bayesopt/surrogate_model.rst
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_model.py
Labels: documentation
