Repository awslabs/syne-tune, pull requests merged in 2023-05, with the labels that each got.

#663 fix: Fix import bug, and also new workflow to install Syne Tune with …
  .github/workflows/integ-tests.yml
  .github/workflows/run-syne-tune.yml
  syne_tune/optimizer/schedulers/multiobjective/nsga2_searcher.py
Labels: fix

#662 feat: Allow to skip initial jobs in remote launching
  benchmarking/commons/launch_remote_common.py
  benchmarking/commons/launch_remote_local.py
  benchmarking/commons/launch_remote_sagemaker.py
  benchmarking/commons/launch_remote_simulator.py
  docs/source/tutorials/benchmarking/bm_local.rst
  docs/source/tutorials/benchmarking/bm_sagemaker.rst
  docs/source/tutorials/benchmarking/bm_simulator.rst
Labels: feature

#652 feat: Plotting tools for result of comparative study
  benchmarking/examples/benchmark_hypertune/plot_results.py
  docs/source/benchmarking/benchmark_hypertune.rst
  docs/source/faq.rst
  docs/source/index.rst
  docs/source/tutorials/benchmarking/README.rst
  docs/source/tutorials/benchmarking/bm_plotting.rst
  docs/source/tutorials/benchmarking/img/docs-1-nas201-cifar100.png
  requirements-visual.txt
  setup.py
  syne_tune/experiments/__init__.py
  syne_tune/experiments/aggregate_results.py
  syne_tune/experiments/plot_per_trial.py
  syne_tune/experiments/plotting.py
  syne_tune/experiments/results_utils.py
Labels: feature

#673 feat: Backoff decorator for jobs scheduling
  syne_tune/remote/scheduling.py
  tst/remote_launcher/test_scheduling.py
Labels: feature

#674 chore: add initial multiobjective benchmarking logic
  benchmarking/commons/default_baselines.py
  benchmarking/nursery/benchmark_multiobjective/README.md
  benchmarking/nursery/benchmark_multiobjective/__init__.py
  benchmarking/nursery/benchmark_multiobjective/baselines.py
  benchmarking/nursery/benchmark_multiobjective/benchmark_definitions.py
  benchmarking/nursery/benchmark_multiobjective/hpo_main.py
  benchmarking/nursery/benchmark_multiobjective/launch_remote.py
  docs/source/tutorials/multifidelity/mf_setup.rst
  tst/benchmarking/benchmark_commons/test_hpo_main_local.py
  tst/schedulers/multiobjective/test_simple_scalarizer.py
Labels: chore

#672 fix: Domain.len returns 0 for infinite domain (e.g., Float)
  syne_tune/config_space.py
  syne_tune/optimizer/schedulers/searchers/regularized_evolution.py
  tst/schedulers/test_rea.py
Labels: fix

#681 fix: Sklearn estimator now fits the surrogate model without considering pending evaluations.
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_estimator.py
  tst/schedulers/bayesopt/test_sklearn_surrogate.py
Labels: bug

#682 fix: Made scoring function compatible with acquisition function interface
  syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/base_classes.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/tuning_algorithms/bo_algorithm_components.py
Labels: bug, chore

#692 fix: Remove (CITATION?). Currently, these results are not published a…
  docs/source/tutorials/multifidelity/mf_comparison.rst
Labels: fix

#693 fix: New benchmarks need **kwargs, so that defaults can be overwritte…
  benchmarking/commons/benchmark_definitions/finetune_transformer_glue.py
  benchmarking/commons/benchmark_definitions/finetune_transformer_swag.py
  benchmarking/commons/benchmark_definitions/lstm_wikitext2.py
  benchmarking/commons/benchmark_definitions/resnet_cifar10.py
  benchmarking/commons/benchmark_definitions/transformer_wikitext2.py
  docs/source/tutorials/benchmarking/bm_local.rst
Labels: fix

#695 chore: enable caching for unit tests, fix README typo
  .github/workflows/unit-tests.yml
  README.md
Labels: chore

#684 feat: Adding new searcher that uses contributed surrogate models.
  examples/launch_contributed_surrogate_bo.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_estimator.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/models/sklearn_predictor.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/sklearn/estimator.py
  syne_tune/optimizer/schedulers/searchers/bayesopt/sklearn/predictor.py
  syne_tune/optimizer/schedulers/searchers/sklearn/__init__.py
  syne_tune/optimizer/schedulers/searchers/sklearn/sklearn_surrogate_searcher.py
  tst/schedulers/bayesopt/test_sklearn_surrogate.py
  tst/schedulers/test_schedulers_api.py
  tst/util_test.py
Labels: feature

#694 feat: Some extra plotting features
  docs/source/tutorials/visualization/code/plot_learning_curves.py
  docs/source/tutorials/visualization/comparisons.rst
  syne_tune/experiments/plot_per_trial.py
  syne_tune/experiments/plotting.py
Labels: feature
